In [144]:
import numpy as np

In [145]:
import sys
sys.version

'3.12.7 | packaged by Anaconda, Inc. | (main, Oct  4 2024, 13:17:27) [MSC v.1929 64 bit (AMD64)]'

In [146]:
np.__version__

'1.26.4'

### creating arrays

In [147]:
my_list = [0,1,2,3,4,5]#create list
my_list

[0, 1, 2, 3, 4, 5]

In [148]:
type(my_list)

list

In [150]:
arr=np.array(my_list)
arr

array([0, 1, 2, 3, 4, 5])

In [151]:
type(arr) #nd array

numpy.ndarray

In [152]:
print(type(arr))
print(type(my_list))

<class 'numpy.ndarray'>
<class 'list'>


In [153]:
import numpy as np

In [154]:
np.arange(10)   #np.tab we can see 217 functions #

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [155]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [156]:
np.arange(10,50,5)

array([10, 15, 20, 25, 30, 35, 40, 45])

In [157]:
np.arange(10,30,30,5) #4 we can't pass as arguments, start,stop,end

TypeError: Cannot interpret '5' as a data type

In [158]:
np.arange(20,8) # in 1st/arange fun 1st is < 2nd argyment

array([], dtype=int32)

In [159]:
np.arange(-20,8) #refers to hash/comment

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7])

In [160]:
n=np.arange(-20,8) # n is an object/variable
n    #garbage collection the variable is not used goes into it

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7])

In [161]:
np.zeros(3) #parameter

array([0., 0., 0.])

In [162]:
np.zeros(3,dtype=int) #user change sys parameter is hyperparameter tunning,big sysytem,hypertunning

array([0, 0, 0])

In [163]:
z=np.zeros(5) #type is float ,with one aru
z

array([0., 0., 0., 0., 0.])

In [164]:
np.zeros((2,2), dtype=int) #two rows,two coloums matrix 2d array

array([[0, 0],
       [0, 0]])

In [165]:
np.zeros((3,3),dtype=int) #3x3 or 3/3 matrix 3 by default belong to rows ,columns

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [166]:
nd=np.zeros((5,9),dtype=int)
nd

array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [167]:
zero = np.zeros([2,2])
print(zero)
print(type(zero))

[[0. 0.]
 [0. 0.]]
<class 'numpy.ndarray'>


In [168]:
zero=np.zeros([2,2])
print(zero)
print('###')
print(type(zero))

[[0. 0.]
 [0. 0.]]
###
<class 'numpy.ndarray'>


In [169]:
np.zeros((2,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [170]:
np.zeros((10,30))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0

In [171]:
n=(6,7)
n1=(6,8)
print(np.zeros(n1)) #parameter tunning


[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [172]:
print(np.zeros(n,dtype=int)) ##hypertunning

[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]


In [173]:
n

(6, 7)

In [174]:
n1

(6, 8)

In [175]:
print(np.zeros(n1))

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [176]:
np.ones(3)

array([1., 1., 1.])

In [177]:
nd1=np.ones((10,10),dtype=int)
nd1

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [178]:
np.ones(3, dtype=int)

array([1, 1, 1])

In [179]:
np.three(3) #zeros and ones it works,2s and 3s it wont allowed

AttributeError: module 'numpy' has no attribute 'three'

In [180]:
np.ones(2)

array([1., 1.])

In [181]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [182]:
np.ones((6,10),dtype=int)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [183]:
np.twos((2,4))

AttributeError: module 'numpy' has no attribute 'twos'

In [184]:
range(5)

range(0, 5)

In [185]:
r=range(5)
r

range(0, 5)

In [186]:
for i in r:
    print(i)

0
1
2
3
4


In [187]:
list(range(5))

[0, 1, 2, 3, 4]

In [188]:
range(1,10)

range(1, 10)

In [189]:
list(range(1,10))

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [190]:
list(range(1,10,3)) #getting with  3 difference printing 1 to 10

[1, 4, 7]

In [191]:
y=list(range(12)) #range with list
y

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [192]:
nd1

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [193]:
rand(3,2)                                                             

NameError: name 'rand' is not defined

In [194]:
import numpy as np

In [195]:
np.random.rand(3,2)

array([[0.53108553, 0.74020988],
       [0.35792657, 0.32160398],
       [0.09481491, 0.11672339]])

In [196]:
np.random.rand(5)

array([0.20717143, 0.18645618, 0.28824145, 0.01236014, 0.61025241])

In [197]:
np.rand(4)

AttributeError: module 'numpy' has no attribute 'rand'

In [198]:
np.random.rand(2)

array([0.00769627, 0.57220569])

In [199]:
np.random.rand(3)

array([0.61020123, 0.1622042 , 0.29122644])

In [200]:
np.random.rand(2,3) 

array([[0.2777307 , 0.124804  , 0.07041882],
       [0.12358358, 0.01045028, 0.68454953]])

In [201]:
np.random.randint(3) #rand gives float,random=integers 

1

In [202]:
np.random.randint(2,10) # 2is inclusive,10 is exclusive

3

In [203]:
np.random.randint(2,10,4) #where 10 is exclusive

array([9, 4, 3, 3])

In [204]:
np.random.randint(30,20,10) #random starts with low to high

ValueError: low >= high

In [205]:
np.random.randint(-30,20,10) 

array([ -8, -14,  17, -11, -28,  -5, -28, -11,  -5,   2])

In [206]:
np.random.randint(9,20,30)

array([12, 15, 18, 11, 10, 12, 18, 11, 11, 14, 16, 11, 13, 16, 19, 12, 13,
       18,  9, 13, 16, 16, 12, 13, 18, 15, 11, 16, 16, 17])

In [207]:
np.random.randint(5,9) ##GET THE VALUE <=1 & >=5

7

In [208]:
np.random.randint(10,21,3)

array([20, 20, 18])

In [209]:
np.random.randint(10,40,(10,10)) #nd array ,for2 nd excution values will change

array([[23, 13, 24, 13, 33, 26, 19, 14, 36, 35],
       [13, 17, 22, 11, 15, 26, 20, 37, 25, 33],
       [28, 25, 39, 19, 22, 19, 11, 19, 16, 27],
       [16, 17, 28, 32, 35, 10, 23, 19, 32, 30],
       [31, 23, 20, 17, 15, 34, 20, 36, 33, 15],
       [35, 18, 11, 22, 29, 33, 24, 34, 37, 15],
       [18, 38, 29, 10, 12, 30, 37, 12, 39, 34],
       [15, 23, 27, 30, 23, 21, 26, 39, 28, 10],
       [16, 17, 29, 20, 12, 14, 20, 27, 14, 28],
       [20, 13, 12, 30, 11, 30, 36, 22, 28, 23]])

In [210]:
np.random.randint(1,100,(12,12)) #generate the element 10-30 4*4 matr

array([[67, 86, 26, 90, 75, 81, 47, 57, 40, 32, 29, 85],
       [60, 84, 85, 28, 16, 96, 39, 73, 46, 68, 98, 61],
       [98, 32, 11, 14, 51, 33, 25, 69, 83, 54, 86, 55],
       [37, 77, 98, 63, 24, 96, 98, 64, 30, 87, 62, 35],
       [26, 45, 20,  3, 18, 28, 94, 99, 51, 98, 65, 29],
       [90, 91, 43, 80, 11, 64, 69, 35, 46, 99,  9, 78],
       [13, 13, 75, 46, 28, 47, 18, 59, 86, 67, 17, 84],
       [95, 46, 57, 22, 28, 88, 91, 12, 15, 30, 12, 90],
       [82, 46, 39, 79, 26, 77, 13, 80, 76, 81, 21, 85],
       [86, 57,  6,  4, 12, 24, 51, 33, 41,  4, 23, 63],
       [99, 41, 98, 28,  4, 71, 31, 72, 67, 60, 88, 58],
       [19, 82, 93, 66, 61, 41, 47, 92, 25,  2, 11, 82]])

In [211]:
np.arange(1,13).reshape(3,4) #reshape:changes the dimension of array without changing the data

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [212]:
np.arange(1,13).reshape(12,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [213]:
m = np.random.randint(10,40,(10,10)) #with variable
m

array([[20, 37, 21, 25, 17, 38, 37, 13, 35, 13],
       [34, 20, 34, 34, 21, 22, 12, 27, 27, 17],
       [17, 16, 15, 20, 12, 28, 26, 36, 21, 36],
       [22, 21, 10, 28, 26, 21, 14, 10, 37, 30],
       [36, 31, 20, 21, 33, 35, 20, 13, 24, 34],
       [25, 21, 34, 19, 37, 13, 18, 21, 18, 25],
       [37, 21, 25, 19, 17, 38, 21, 33, 27, 27],
       [13, 12, 33, 11, 16, 36, 39, 13, 21, 25],
       [31, 18, 35, 34, 15, 10, 27, 24, 33, 17],
       [27, 26, 33, 23, 26, 24, 18, 19, 15, 20]])

In [214]:
type(m)

numpy.ndarray

In [215]:
m

array([[20, 37, 21, 25, 17, 38, 37, 13, 35, 13],
       [34, 20, 34, 34, 21, 22, 12, 27, 27, 17],
       [17, 16, 15, 20, 12, 28, 26, 36, 21, 36],
       [22, 21, 10, 28, 26, 21, 14, 10, 37, 30],
       [36, 31, 20, 21, 33, 35, 20, 13, 24, 34],
       [25, 21, 34, 19, 37, 13, 18, 21, 18, 25],
       [37, 21, 25, 19, 17, 38, 21, 33, 27, 27],
       [13, 12, 33, 11, 16, 36, 39, 13, 21, 25],
       [31, 18, 35, 34, 15, 10, 27, 24, 33, 17],
       [27, 26, 33, 23, 26, 24, 18, 19, 15, 20]])

In [216]:
m[:]

array([[20, 37, 21, 25, 17, 38, 37, 13, 35, 13],
       [34, 20, 34, 34, 21, 22, 12, 27, 27, 17],
       [17, 16, 15, 20, 12, 28, 26, 36, 21, 36],
       [22, 21, 10, 28, 26, 21, 14, 10, 37, 30],
       [36, 31, 20, 21, 33, 35, 20, 13, 24, 34],
       [25, 21, 34, 19, 37, 13, 18, 21, 18, 25],
       [37, 21, 25, 19, 17, 38, 21, 33, 27, 27],
       [13, 12, 33, 11, 16, 36, 39, 13, 21, 25],
       [31, 18, 35, 34, 15, 10, 27, 24, 33, 17],
       [27, 26, 33, 23, 26, 24, 18, 19, 15, 20]])

In [217]:
m[1:3]

array([[34, 20, 34, 34, 21, 22, 12, 27, 27, 17],
       [17, 16, 15, 20, 12, 28, 26, 36, 21, 36]])

In [218]:
m

array([[20, 37, 21, 25, 17, 38, 37, 13, 35, 13],
       [34, 20, 34, 34, 21, 22, 12, 27, 27, 17],
       [17, 16, 15, 20, 12, 28, 26, 36, 21, 36],
       [22, 21, 10, 28, 26, 21, 14, 10, 37, 30],
       [36, 31, 20, 21, 33, 35, 20, 13, 24, 34],
       [25, 21, 34, 19, 37, 13, 18, 21, 18, 25],
       [37, 21, 25, 19, 17, 38, 21, 33, 27, 27],
       [13, 12, 33, 11, 16, 36, 39, 13, 21, 25],
       [31, 18, 35, 34, 15, 10, 27, 24, 33, 17],
       [27, 26, 33, 23, 26, 24, 18, 19, 15, 20]])

In [219]:
m[1,2] 

34

In [220]:
m[1,-1]

17

In [221]:
m

array([[20, 37, 21, 25, 17, 38, 37, 13, 35, 13],
       [34, 20, 34, 34, 21, 22, 12, 27, 27, 17],
       [17, 16, 15, 20, 12, 28, 26, 36, 21, 36],
       [22, 21, 10, 28, 26, 21, 14, 10, 37, 30],
       [36, 31, 20, 21, 33, 35, 20, 13, 24, 34],
       [25, 21, 34, 19, 37, 13, 18, 21, 18, 25],
       [37, 21, 25, 19, 17, 38, 21, 33, 27, 27],
       [13, 12, 33, 11, 16, 36, 39, 13, 21, 25],
       [31, 18, 35, 34, 15, 10, 27, 24, 33, 17],
       [27, 26, 33, 23, 26, 24, 18, 19, 15, 20]])

In [222]:
m[0:-2] 

array([[20, 37, 21, 25, 17, 38, 37, 13, 35, 13],
       [34, 20, 34, 34, 21, 22, 12, 27, 27, 17],
       [17, 16, 15, 20, 12, 28, 26, 36, 21, 36],
       [22, 21, 10, 28, 26, 21, 14, 10, 37, 30],
       [36, 31, 20, 21, 33, 35, 20, 13, 24, 34],
       [25, 21, 34, 19, 37, 13, 18, 21, 18, 25],
       [37, 21, 25, 19, 17, 38, 21, 33, 27, 27],
       [13, 12, 33, 11, 16, 36, 39, 13, 21, 25]])

In [223]:
m[0,2]

21

In [224]:
m

array([[20, 37, 21, 25, 17, 38, 37, 13, 35, 13],
       [34, 20, 34, 34, 21, 22, 12, 27, 27, 17],
       [17, 16, 15, 20, 12, 28, 26, 36, 21, 36],
       [22, 21, 10, 28, 26, 21, 14, 10, 37, 30],
       [36, 31, 20, 21, 33, 35, 20, 13, 24, 34],
       [25, 21, 34, 19, 37, 13, 18, 21, 18, 25],
       [37, 21, 25, 19, 17, 38, 21, 33, 27, 27],
       [13, 12, 33, 11, 16, 36, 39, 13, 21, 25],
       [31, 18, 35, 34, 15, 10, 27, 24, 33, 17],
       [27, 26, 33, 23, 26, 24, 18, 19, 15, 20]])

In [225]:
m[-5,-3]

21

In [226]:
m[-5:-]

SyntaxError: invalid syntax (689909210.py, line 1)

In [227]:
m[-4,2]

25

In [228]:
b=np.random.randint(10,20,(4,4))
b

array([[18, 10, 12, 12],
       [18, 19, 16, 14],
       [16, 15, 18, 16],
       [15, 19, 14, 10]])

In [229]:
b

array([[18, 10, 12, 12],
       [18, 19, 16, 14],
       [16, 15, 18, 16],
       [15, 19, 14, 10]])

In [230]:
b[-4,-2]

12

In [231]:
b[-4:2]

array([[18, 10, 12, 12],
       [18, 19, 16, 14]])

In [232]:
np.random.randint(10,20,(4,4))

array([[12, 17, 15, 14],
       [13, 17, 10, 16],
       [10, 15, 18, 16],
       [11, 11, 11, 11]])

In [233]:
b

array([[18, 10, 12, 12],
       [18, 19, 16, 14],
       [16, 15, 18, 16],
       [15, 19, 14, 10]])

In [234]:
b[-4,-2]

12

In [235]:
b

array([[18, 10, 12, 12],
       [18, 19, 16, 14],
       [16, 15, 18, 16],
       [15, 19, 14, 10]])

In [236]:
b[-4,-2]

12

In [237]:
b[:]

array([[18, 10, 12, 12],
       [18, 19, 16, 14],
       [16, 15, 18, 16],
       [15, 19, 14, 10]])

### operations

In [238]:
a = np.random.randint(10,20,10)
a

array([18, 12, 13, 10, 12, 11, 11, 19, 14, 19])

In [239]:
id(a)

1371465579280

In [240]:
arr

array([0, 1, 2, 3, 4, 5])

In [241]:
arr2 =np.random.randint(0,100,(10,10))
arr2

array([[69, 63, 45, 95, 67, 57, 70, 45, 65, 10],
       [65, 40, 74, 81, 85, 84, 28, 21, 31, 25],
       [ 5, 97, 47, 92, 38, 24, 72, 99, 97,  0],
       [ 7, 91, 59, 83, 17,  5,  5, 84, 76, 13],
       [82, 91, 44, 58,  2, 27, 21, 78, 87, 94],
       [17,  2, 11, 57, 75, 12, 20, 29, 32, 76],
       [18, 93, 89, 85, 62, 37, 34, 61, 21, 77],
       [80, 78, 84, 83, 22, 98, 80, 36, 72, 73],
       [33, 60, 40, 78, 84, 94, 93, 79,  3, 44],
       [88,  5, 50, 71, 95, 80, 16,  6, 57, 95]])

In [242]:
arr[:]

array([0, 1, 2, 3, 4, 5])

In [243]:
arr[:4]

array([0, 1, 2, 3])

In [244]:
arr2[:2]

array([[69, 63, 45, 95, 67, 57, 70, 45, 65, 10],
       [65, 40, 74, 81, 85, 84, 28, 21, 31, 25]])

In [245]:
arr2[:4]

array([[69, 63, 45, 95, 67, 57, 70, 45, 65, 10],
       [65, 40, 74, 81, 85, 84, 28, 21, 31, 25],
       [ 5, 97, 47, 92, 38, 24, 72, 99, 97,  0],
       [ 7, 91, 59, 83, 17,  5,  5, 84, 76, 13]])

In [246]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [247]:
arr2

array([[69, 63, 45, 95, 67, 57, 70, 45, 65, 10],
       [65, 40, 74, 81, 85, 84, 28, 21, 31, 25],
       [ 5, 97, 47, 92, 38, 24, 72, 99, 97,  0],
       [ 7, 91, 59, 83, 17,  5,  5, 84, 76, 13],
       [82, 91, 44, 58,  2, 27, 21, 78, 87, 94],
       [17,  2, 11, 57, 75, 12, 20, 29, 32, 76],
       [18, 93, 89, 85, 62, 37, 34, 61, 21, 77],
       [80, 78, 84, 83, 22, 98, 80, 36, 72, 73],
       [33, 60, 40, 78, 84, 94, 93, 79,  3, 44],
       [88,  5, 50, 71, 95, 80, 16,  6, 57, 95]])

In [248]:
arr2[1,4]

85

In [249]:
arr2[-5,5]

12

In [250]:
arr2[-5,-5]

12

In [251]:
arr2[-1,-2]

57

In [252]:
arr2[::-1] #prints 1 and leaves two ,with reverse function

array([[88,  5, 50, 71, 95, 80, 16,  6, 57, 95],
       [33, 60, 40, 78, 84, 94, 93, 79,  3, 44],
       [80, 78, 84, 83, 22, 98, 80, 36, 72, 73],
       [18, 93, 89, 85, 62, 37, 34, 61, 21, 77],
       [17,  2, 11, 57, 75, 12, 20, 29, 32, 76],
       [82, 91, 44, 58,  2, 27, 21, 78, 87, 94],
       [ 7, 91, 59, 83, 17,  5,  5, 84, 76, 13],
       [ 5, 97, 47, 92, 38, 24, 72, 99, 97,  0],
       [65, 40, 74, 81, 85, 84, 28, 21, 31, 25],
       [69, 63, 45, 95, 67, 57, 70, 45, 65, 10]])

In [253]:
arr2[::-2]

array([[88,  5, 50, 71, 95, 80, 16,  6, 57, 95],
       [80, 78, 84, 83, 22, 98, 80, 36, 72, 73],
       [17,  2, 11, 57, 75, 12, 20, 29, 32, 76],
       [ 7, 91, 59, 83, 17,  5,  5, 84, 76, 13],
       [65, 40, 74, 81, 85, 84, 28, 21, 31, 25]])

In [254]:
arr.max() #prints  maximum value

5

In [255]:
arr.min()#prints minimum value

0

In [256]:
arr

array([0, 1, 2, 3, 4, 5])

In [257]:
arr.mean()

2.5

In [258]:
arr.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [259]:
from numpy import *
a= array([1,5,6,9,8])
median(a)

6.0

### without work on import* finding median,mode

In [260]:
arr

array([0, 1, 2, 3, 4, 5])

In [263]:
arr.reshape(2,5) #take the multiplication of array size(10)

ValueError: cannot reshape array of size 6 into shape (2,5)

In [264]:
arr.reshape(10,1)

ValueError: cannot reshape array of size 6 into shape (10,1)

In [265]:
arr.reshape(2,3,order='C')

array([[0, 1, 2],
       [3, 4, 5]])

In [266]:
arr.reshape(2,3,order='F') #print element with fortran

array([[0, 2, 4],
       [1, 3, 5]])

In [267]:
arr.reshape(2,3,order='A') # A almost give C type output

array([[0, 1, 2],
       [3, 4, 5]])

In [268]:
arr

array([0, 1, 2, 3, 4, 5])

In [269]:
arr.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [270]:
arr.reshape(2,1)

ValueError: cannot reshape array of size 6 into shape (2,1)

In [271]:
arr.reshape(1,6)

array([[0, 1, 2, 3, 4, 5]])

In [272]:
arr.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [276]:
arr.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

## Indexing

In [278]:
mat = np.arange(0,100).reshape(10,10)
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [281]:
row=4
col=5

In [282]:
col

5

In [283]:
row

4

In [284]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [285]:
mat[row,col]

45

In [287]:
mat[4,5]

45

In [286]:
mat[:] #slicing: printed full mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [288]:
col = 6

In [289]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [290]:
mat[6] #default it represent to rows

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [291]:
mat[:col]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [292]:
mat[row,:]

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [293]:
mat[:,8]

array([ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98])

In [294]:
mat[:col]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [295]:
mat[:6]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [296]:
row

4

In [297]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [298]:
mat[:row]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [299]:
mat[:,-8]

array([ 2, 12, 22, 32, 42, 52, 62, 72, 82, 92])

In [300]:
mat[:-1]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89]])

In [301]:
mat[1,4]

14

In [302]:
mat[1:4]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [303]:
mat[3:-3]

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [304]:
mat[0]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [305]:
mat[6]

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [306]:
mat[6:]

array([[60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [307]:
mat[:6]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [308]:
mat[5:7]

array([[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [309]:
mat[0:10]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [310]:
mat[0:10:3]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [311]:
mat[0:10]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [312]:
mat[4:]

array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [313]:
mat[:4]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [314]:
mat[::-1]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [315]:
mat[::-3]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [316]:
mat[::-5]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [317]:
mat[2:6]

array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [318]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [320]:
mat[2:6,2:4]

array([[22, 23],
       [32, 33],
       [42, 43],
       [52, 53]])

In [321]:
mat[0,1]

1

In [322]:
mat[1,6]

16

In [323]:
mat[:1]

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [324]:
mat[:6]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [325]:
mat[3,5]

35

In [326]:
mat[1:2,2:4]

array([[12, 13]])

In [327]:
mat[2:3,2:3]

array([[22]])

In [328]:
mat[2:4,3:5]

array([[23, 24],
       [33, 34]])

In [329]:
mat[2:3,4:5]

array([[24]])

### Masking

In [330]:
mat # we also calles filter

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [331]:
id(mat)

1371466400368

In [332]:
mat[mat<50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [333]:
mat[mat<=50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [334]:
mat[mat==50]

array([50])

In [335]:
mat==50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [ True, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [337]:
a1=mat[mat<50]
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [339]:
a2=mat[mat>50]
a2

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [341]:
a3=mat[mat<=50]
a3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [342]:
a4=mat[mat==50]
a4

array([50])