In [3]:
import numpy as np

In [2]:
import sys
sys.version

'3.12.7 | packaged by Anaconda, Inc. | (main, Oct  4 2024, 13:17:27) [MSC v.1929 64 bit (AMD64)]'

In [4]:
np.__version__

'1.26.4'

In [16]:
my_list = [0,1,2,3,4,5]#create list
my_list

[0, 1, 2, 3, 4, 5]

In [17]:
type(my_list)

list

In [10]:
arr=np.array(my_list)
arr

array([0, 1, 2, 3, 4, 5])

In [13]:
type(arr) #nd array

numpy.ndarray

In [18]:
print(type(arr))
print(type(my_list))

<class 'numpy.ndarray'>
<class 'list'>


In [6]:
import numpy as np

In [7]:
np.arange(10)   #np.tab we can see 217 functions #

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [9]:
np.arange(10,50,5)

array([10, 15, 20, 25, 30, 35, 40, 45])

In [10]:
np.arange(10,30,30,5) #4 we can't pass as arguments, start,stop,end

TypeError: Cannot interpret '5' as a data type

In [11]:
np.arange(20,8) # in 1st/arange fun 1st is < 2nd argyment

array([], dtype=int32)

In [12]:
np.arange(-20,8) #refers to hash/comment

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7])

In [13]:
n=np.arange(-20,8) # n is an object/variable
n    #garbage collection the variable is not used goes into it

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7])

In [14]:
np.zeros(3) #parameter

array([0., 0., 0.])

In [15]:
np.zeros(3,dtype=int) #user change sys parameter is hyperparameter tunning,big sysytem,hypertunning

array([0, 0, 0])

In [16]:
z=np.zeros(5) #type is float ,with one aru
z

array([0., 0., 0., 0., 0.])

In [17]:
np.zeros((2,2)) #two rows,two coloums matrix 2d array

array([[0., 0.],
       [0., 0.]])

In [18]:
np.zeros((3,3),dtype=int) #3x3 or 3/3 matrix 3 by default belong to rows ,columns

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [19]:
nd=np.zeros((5,9),dtype=int)
nd

array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [20]:
np.ones(3)

array([1., 1., 1.])

In [21]:
np.ones(3, dtype=int)

array([1, 1, 1])

In [22]:
nd1=np.ones((10,10),dtype=int)
nd1

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [23]:
np.three(3) #zeros and ones it works

AttributeError: module 'numpy' has no attribute 'three'

In [24]:
nd1

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])